import { useState, useEffect } from 'react'
import { supabase } from '../lib/supabase'

interface FirewallRule {
  id: string
  name: string
  action: string
  protocol: string
  source_ip: string
  source_port: string
  dest_ip: string
  dest_port: string
  direction: string
  enabled: boolean
  created_at: string
}

const ACTION_COLORS: Record<string, string> = {
  allow: '#00ff9d',
  drop: '#ff3366',
  reject: '#ff6b35',
}

export default function FirewallBuilder() {
  const [rules, setRules] = useState<FirewallRule[]>([])
  const [loading, setLoading] = useState(true)
  const [showForm, setShowForm] = useState(false)
  const [form, setForm] = useState({
    name: '',
    action: 'allow',
    protocol: 'tcp',
    source_ip: 'any',
    source_port: 'any',
    dest_ip: 'any',
    dest_port: 'any',
    direction: 'inbound',
  })

  useEffect(() => {
    loadRules()
  }, [])

  async function loadRules() {
    if (!supabase) {
      setRules([])
      setLoading(false)
      return
    }
    const { data, error } = await supabase
      .from('firewall_rules')
      .select('*')
      .order('created_at', { ascending: false })
    if (error) console.error('Error loading rules:', error)
    setRules(data || [])
    setLoading(false)
  }

  async function addRule() {
    if (!form.name.trim() || !supabase) return
    const { data, error } = await supabase
      .from('firewall_rules')
      .insert([{ ...form, enabled: true }])
      .select()
    if (error) {
      console.error('Error adding rule:', error)
      return
    }
    if (data) setRules([data[0], ...rules])
    setForm({ name: '', action: 'allow', protocol: 'tcp', source_ip: 'any', source_port: 'any', dest_ip: 'any', dest_port: 'any', direction: 'inbound' })
    setShowForm(false)
  }

  async function toggleRule(id: string, enabled: boolean) {
    if (!supabase) return
    const { error } = await supabase
      .from('firewall_rules')
      .update({ enabled: !enabled })
      .eq('id', id)
    if (error) {
      console.error('Error toggling rule:', error)
      return
    }
    setRules(rules.map(r => r.id === id ? { ...r, enabled: !enabled } : r))
  }

  async function deleteRule(id: string) {
    if (!supabase) return
    const { error } = await supabase
      .from('firewall_rules')
      .delete()
      .eq('id', id)
    if (error) {
      console.error('Error deleting rule:', error)
      return
    }
    setRules(rules.filter(r => r.id !== id))
  }

  function exportRules() {
    const iptables = rules.map(r => {
      const action = r.action === 'allow' ? 'ACCEPT' : r.action === 'drop' ? 'DROP' : 'REJECT'
      const dir = r.direction === 'inbound' ? 'INPUT' : 'OUTPUT'
      const proto = r.protocol === 'any' ? '' : `-p ${r.protocol}`
      const src = r.source_ip === 'any' ? '' : `-s ${r.source_ip}`
      const sport = r.source_port === 'any' ? '' : `--sport ${r.source_port}`
      const dport = r.dest_port === 'any' ? '' : `--dport ${r.dest_port}`
      const dst = r.dest_ip === 'any' ? '' : `-d ${r.dest_ip}`
      return `iptables -A ${dir} ${proto} ${src} ${dst} ${sport} ${dport} -j ${action}  # ${r.name}`
    }).join('\n')

    const blob = new Blob([`# Firewall Rules Export\n# Generated by CyberSec Toolkit\n# ${new Date().toISOString()}\n\n${iptables}`], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'firewall_rules.conf'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-4">
      <div className="flex gap-2 flex-wrap">
        <button onClick={() => setShowForm(!showForm)} className="cyber-btn cyber-btn-primary">
          {showForm ? 'Cancel' : '+ Add Firewall Rule'}
        </button>
        {rules.length > 0 && (
          <button onClick={exportRules} className="cyber-btn cyber-btn-ghost">
            Export as iptables
          </button>
        )}
      </div>

      {showForm && (
        <div className="cyber-card p-4 space-y-3 fade-in">
          <input type="text" placeholder="Rule name (e.g. Block SSH from external)" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="cyber-input w-full font-mono text-[13px]" />
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            <div>
              <label className="cyber-label">Action</label>
              <select value={form.action} onChange={e => setForm({ ...form, action: e.target.value })} className="cyber-input-sm w-full font-mono">
                {['allow', 'drop', 'reject'].map(a => <option key={a} value={a}>{a}</option>)}
              </select>
            </div>
            <div>
              <label className="cyber-label">Direction</label>
              <select value={form.direction} onChange={e => setForm({ ...form, direction: e.target.value })} className="cyber-input-sm w-full font-mono">
                {['inbound', 'outbound'].map(d => <option key={d} value={d}>{d}</option>)}
              </select>
            </div>
            <div>
              <label className="cyber-label">Protocol</label>
              <select value={form.protocol} onChange={e => setForm({ ...form, protocol: e.target.value })} className="cyber-input-sm w-full font-mono">
                {['tcp', 'udp', 'icmp', 'any'].map(p => <option key={p} value={p}>{p}</option>)}
              </select>
            </div>
            <div>
              <label className="cyber-label">Source IP</label>
              <input type="text" placeholder="any" value={form.source_ip} onChange={e => setForm({ ...form, source_ip: e.target.value })} className="cyber-input-sm w-full font-mono" />
            </div>
            <div>
              <label className="cyber-label">Source Port</label>
              <input type="text" placeholder="any" value={form.source_port} onChange={e => setForm({ ...form, source_port: e.target.value })} className="cyber-input-sm w-full font-mono" />
            </div>
            <div>
              <label className="cyber-label">Dest IP</label>
              <input type="text" placeholder="any" value={form.dest_ip} onChange={e => setForm({ ...form, dest_ip: e.target.value })} className="cyber-input-sm w-full font-mono" />
            </div>
            <div>
              <label className="cyber-label">Dest Port</label>
              <input type="text" placeholder="any" value={form.dest_port} onChange={e => setForm({ ...form, dest_port: e.target.value })} className="cyber-input-sm w-full font-mono" />
            </div>
          </div>
          <button onClick={addRule} disabled={!form.name.trim()} className="cyber-btn cyber-btn-primary disabled:opacity-30">
            Create Rule
          </button>
        </div>
      )}

      {loading ? (
        <div className="text-center py-8 text-cyber-muted font-mono text-sm">Loading firewall rules...</div>
      ) : rules.length === 0 ? (
        <div className="text-center py-8 text-cyber-muted font-mono text-sm">
          No firewall rules configured. Click "Add Firewall Rule" to create one.
        </div>
      ) : (
        <div className="space-y-2">
          {rules.map(rule => (
            <div key={rule.id} className={`cyber-card p-3 border-l-4 fade-in ${!rule.enabled ? 'opacity-50' : ''}`} style={{ borderLeftColor: ACTION_COLORS[rule.action] }}>
              <div className="flex items-center justify-between">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-bold text-[13px] text-cyber-text-bright truncate">{rule.name}</span>
                    <span className="cyber-badge" style={{ background: `${ACTION_COLORS[rule.action]}20`, color: ACTION_COLORS[rule.action] }}>
                      {rule.action}
                    </span>
                    <span className="text-2xs font-mono text-cyber-muted">{rule.direction}</span>
                  </div>
                  <div className="text-2xs font-mono text-cyber-muted mt-1">
                    {rule.protocol.toUpperCase()} | {rule.source_ip}:{rule.source_port} → {rule.dest_ip}:{rule.dest_port}
                  </div>
                </div>
                <div className="flex items-center gap-2 shrink-0 ml-2">
                  <button onClick={() => toggleRule(rule.id, rule.enabled)} className={`text-2xs font-mono px-2 py-1 rounded font-bold ${rule.enabled ? 'text-cyber-primary' : 'text-cyber-muted'}`}>
                    {rule.enabled ? 'ON' : 'OFF'}
                  </button>
                  <button onClick={() => deleteRule(rule.id)} className="text-cyber-muted hover:text-cyber-danger">✕</button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
